
development:
  adapter: postgresql
  encoding: unicode
  database: lost_tribes_3_development
  pool: 5
<<<<<<< HEAD
  username: chriseichler
  host: localhost
=======
  username: michaelreinhart
  password:
>>>>>>> chris

test:
  adapter: postgresql
  encoding: unicode
  database: lost_tribes_3_test
  pool: 5
<<<<<<< HEAD
  username: chriseichler
  host: localhost

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: lost_tribes_3_production
#   pool: 5
#   username: chriseichler
#   password:


=======
  username: michaelreinhart
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: lost_tribes_3_production
  pool: 5
  username: michaelreinhart
  password:
>>>>>>> chris
