
development:
  adapter: postgresql
  encoding: unicode
  database: lost_tribes_3_development
  pool: 5
<<<<<<< HEAD
  username: ryankuhel
  password:
=======
  username: michaelreinhart
>>>>>>> 304fbd4cd401a1d86302a223520e391e807f4e66
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: lost_tribes_3_test
  pool: 5
<<<<<<< HEAD
  username: ryankuhel
  password:
=======
  username: michaelreinhart
>>>>>>> 304fbd4cd401a1d86302a223520e391e807f4e66
  host: localhost


production:
  adapter: postgresql
  encoding: unicode
  database: lost_tribes_3_production
  pool: 5
  username: ryankuhel
  password:
  host: localhost





