
development:
  adapter: postgresql
  encoding: unicode
  database: lost_tribes_3_development
  pool: 5
  password:
  username: chriseichler
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: lost_tribes_3_test
  pool: 5
  password:
  username: chriseichler
  host: localhost


production:
  adapter: postgresql
  encoding: unicode
  database: lost_tribes_3_production
  pool: 5
  username: chriseichler
  password:
  host: localhost





